///////////////////////////////////////////////////////////////////////
// XBeamRate - Cross Beam Load Rating
// Copyright © 1999-2018  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// XBeamRate.idl : IDL source for XBeamRate.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (XBeamRate.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLCore.idl"; // for the Agent plugin
import "PGSuperIEPlugin.idl";  // for the Importer/Exporter plugins


[
	uuid(CDAAC48F-11E7-46a3-B186-8C5418EB611F),
	version(1.0),
	helpstring("XBRate Type Library")
]
library XBeamRateLibrary
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(B195CE70-2D27-4fa6-B0E5-99D09022D662),
		helpstring("XBRate Application Plugin")
	]
	coclass XBeamRateAppPlugin
	{
		[default] interface IUnknown;
	};

   [
      uuid(8CB5644D-5CC5-4fca-A86C-0A1D566D30CB),
		helpstring("XBRate Component Information")
   ]
   coclass XBeamRateComponentInfo
   {
      interface IUnknown;
   }

   // This agent is an extension agent for PGSuper and PGSplice
	[
		uuid(60BF2930-673C-4d29-B654-8A2E0879DE2B),
		helpstring("XBeamRateAgent Class")
	]
	coclass XBeamRateAgent
	{
		[default] interface IAgentEx;
	};


   [
      uuid(DA6D93DF-1907-4e12-A649-30E2078FFC8A)
   ]
   coclass PGSuperComponentInfo
   {
		[default] interface IUnknown;
   };

   [
      uuid(D9B7C5C6-0233-48cb-89F5-C85AD9A82E2D)
   ]
   coclass PGSpliceComponentInfo
   {
		[default] interface IUnknown;
   };

	[
		uuid(B3773B17-08A0-4f2b-99E8-C8077C3D2166),
		helpstring("PGSuperDataExporter Class")
	]
	coclass PGSuperDataExporter
	{
		[default] interface IPGSDataExporter;
	};
};
