//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProjectAgent.rc
//
#define IDS_PROJNAME                    100
#define IDR_PROJECTAGENT                101
#define IDS_NWC_MESSAGE                 101
#define IDR_PROJECTAGENTMODULE          102
#define IDS_LWC_MESSAGE                 102
#define IDD_CAPACITY_OPTIONS            102
#define IDD_PIER_LAYOUT_PAGE            106
#define IDD_BEARINGS_PAGE               202
#define IDD_SUPERSTRUCTURE_LAYOUT_PAGE  204
#define IDD_LIVE_LOAD_REACTIONS         205
#define IDD_RATING_OPTIONS              206
#define IDD_PROJECTPROPERTIES           207
#define IDC_LF_PERMIT_ROUTINE           208
#define IDC_LF_PERMIT_ROUTINE_SERVICEI  209
#define IDC_DECK_ELEVATION              211
#define IDC_DECK_ELEVATION_UNIT         212
#define IDC_CPO                         213
#define IDC_CPO_UNIT                    214
#define IDC_BLO                         215
#define IDC_BLO_UNIT                    216
#define IDC_SKEW                        217
#define IDC_BEARING_LINE_COUNT          218
#define IDC_BACK_REF_BEARING_LIST       219
#define IDC_AHEAD_REF_BEARING_LIST      220
#define IDC_BACK_REF_BEARING_LOCATION   221
#define IDC_AHEAD_REF_BEARING_LOCATION  222
#define IDC_BACK_REF_BEARING_LOCATION_UNIT 223
#define IDC_AHEAD_REF_BEARING_LOCATION_UNIT 224
#define IDC_BACK_REF_BEARING_DATUM      225
#define IDC_AHEAD_REF_BEARING_DATUM     226
#define IDC_ADD_BACK                    227
#define IDC_ADD_AHEAD                   228
#define IDC_REMOVE_BACK                 229
#define IDC_REMOVE_AHEAD                230
#define IDC_BACK_LABEL                  231
#define IDC_AHEAD_LABEL                 232
#define IDC_COPY_AHEAD                  233
#define IDC_COPY_BACK                   234
#define IDC_PIER_TYPE                   234
#define IDC_AHEAD_BEARING_LABEL         235
#define IDC_AHEAD_BEARING_LABEL1        236
#define IDC_AHEAD_BEARING_LABEL2        237
#define IDC_AHEAD_BEARING_LABEL3        238
#define IDC_DIMENSIONS                  239
#define IDC_CURB_LINE_MEASUREMENT       240
#define IDC_LCO                         241
#define IDC_LCO_UNIT                    242
#define IDC_RCO                         243
#define IDC_RCO_UNIT                    244
#define IDC_SL                          245
#define IDC_SL_UNIT                     246
#define IDC_SR                          247
#define IDC_LF_LEGAL_SPECIAL            247
#define IDC_SR_UNIT                     248
#define IDC_DW                          250
#define IDC_DW_STRENGTH_I               250
#define IDC_LF_OPERATING                250
#define IDC_DESIGN_GRID                 251
#define IDC_DW_SERVICE_I                251
#define IDC_LEGAL_ROUTINE_GRID          252
#define IDC_DW_STRENGTH_II              252
#define IDC_LEGAL_SPECIAL_GRID          253
#define IDC_PERMIT_ROUTINE_GRID         254
#define IDC_PERMIT_SPECIAL_GRID         255
#define IDC_DESIGN_ADD                  256
#define IDC_DESIGN_REMOVE               257
#define IDC_LEGAL_ROUTINE_ADD           260
#define IDC_LEGAL_ROUTINE_REMOVE        261
#define IDC_DC_STRENGTH_I               261
#define IDC_LEGAL_SPECIAL_ADD           262
#define IDC_DC_SERVICE_I                262
#define IDC_LEGAL_SPECIAL_REMOVE        263
#define IDC_DC_STRENGTH_II              263
#define IDC_PERMIT_ROUTINE_ADD          264
#define IDC_PERMIT_ROUTINE_REMOVE       265
#define IDC_PERMIT_SPECIAL_ADD          266
#define IDC_PERMIT_SPECIAL_REMOVE       267
#define IDC_LF_INVENTORY                268
#define IDC_LF_LEGAL_ROUTINE            269
#define IDC_LF_PERMIT_SPECIAL           270
#define IDC_LF_PERMIT_SPECIAL2          271
#define IDC_LF_PERMIT_SPECIAL_SERVICEI  271
#define IDD_CONCRETE_DETAILS            280
#define IDC_CONCRETE_TYPE               281
#define IDC_FC_LABEL                    282
#define IDC_FC                          283
#define IDC_FC_UNIT                     284
#define IDC_DS_TITLE                    285
#define IDC_DS                          286
#define IDC_DS_UNIT                     287
#define IDC_COLUMN_GRID                 287
#define IDC_ADD_COLUMN                  288
#define IDC_DW_UNIT                     289
#define IDC_REMOVE_COLUMN               289
#define IDC_MOD_E                       290
#define IDC_BACK_REACTION_TYPE          290
#define IDC_AHEAD_REACTION_TYPE         291
#define IDC_EC                          291
#define IDC_BACK_REACTION_TYPE_LABEL    292
#define IDC_EC_UNIT                     292
#define IDC_AHEAD_REACTION_TYPE_LABEL   293
#define IDC_AGG_SIZE                    293
#define IDC_AGG_SIZE_UNIT               294
#define IDC_CR_STRENGTH_I               294
#define IDC_SH_STRENGTH_I               295
#define IDC_PS_STRENGTH_I               296
#define IDC_SLAB_DEPTH                  297
#define IDC_CR_SERVICE_I                297
#define IDC_SLAB_DEPTH_UNIT             298
#define IDC_SH_SERVICE_I                298
#define IDC_BACK_BRG_OFFSET             299
#define IDC_AHEAD_BRG_OFFSET            300
#define IDC_BACK_BRG_OFFSET_UNIT        301
#define IDC_AHEAD_BRG_OFFSET_UNIT       302
#define IDC_BACK_BRG_OFFSET_LABEL1      303
#define IDC_REACTION_APPLICATION        303
#define IDC_AHEAD_BRG_OFFSET_LABEL1     304
#define IDC_COMBO1                      304
#define IDC_PERMIT_FACTORS              304
#define IDC_BACK_BRG_OFFSET_LABEL2      305
#define IDC_DESIGN_RATING               305
#define IDC_AHEAD_BRG_OFFSET_LABEL2     306
#define IDC_DESIGN_SHEAR                306
#define IDC_LEGAL_RATING                307
#define IDC_PS_SERVICE_I                307
#define IDC_LEGAL_SHEAR                 308
#define IDC_CR_STRENGTH_II              308
#define IDC_PERMIT_RATING               309
#define IDC_SH_STRENGTH_II              309
#define IDC_PERMIT_SHEAR                310
#define IDC_PS_STRENGTH_I2              310
#define IDC_PS_STRENGTH_II              310
#define IDC_PERMIT_YIELD_STRESS         311
#define IDC_ALLOWABLE_STRESS_LABEL      312
#define IDC_ALLOWABLE_STRESS            313
#define IDC_ALLOWABLE_STRESS_TAG        314
#define IDC_PHI_COMPRESSION             315
#define IDC_PHI_TENSION                 316
#define IDC_EDIT3                       317
#define IDC_PHI_SHEAR                   317
#define IDC_SYSTEM_FACTOR_FLEXURE       319
#define IDC_SYSTEM_FACTOR_SHEAR         320
#define IDC_LRFD_LABEL                  321
#define IDC_LRFR_LABEL                  322
#define IDC_LRFD                        323
#define IDC_LRFR                        324
#define IDC_LL_STEP                     324
#define IDC_LL_STEP_UNIT                325
#define IDD_AASHTO_CONCRETE             500
#define IDB_EDIT_PIER                   500
#define IDC_EC_K1_LABEL                 501
#define IDB_EDIT_OPTIONS                501
#define IDD_ANALYSIS_OPTIONS            501
#define IDC_EC_K1                       502
#define IDC_EC_K2_LABEL                 503
#define IDC_EC_K2                       504
#define IDC_CREEP_K1_LABEL              505
#define IDC_CREEP_K1                    506
#define IDC_CREEP_K2_LABEL              507
#define IDC_CREEP_K2                    508
#define IDC_SHRINKAGE_K1_LABEL          509
#define IDC_SHRINKAGE_K1                510
#define IDC_SHRINKAGE_K2_LABEL          511
#define IDC_SHRINKAGE_K2                512
#define IDC_HAS_AGG_STRENGTH            513
#define IDC_AGG_STRENGTH                514
#define IDC_AGG_STRENGTH_T              515
#define IDC_CONDITION_FACTOR            1260
#define IDC_CONDITION_FACTOR_TYPE       1407
#define IDC_REFCOLUMN_MEASUREMENT       1423
#define IDC_REFCOLUMN_OFFSET            1424
#define IDC_REFCOLUMN_OFFSET_UNIT       1425
#define IDC_BACK_BEARING_GRID           1475
#define IDC_AHEAD_BEARING_GRID          1476
#define IDC_REFCOLUMN                   1546
#define IDC_X5                          1617
#define IDC_HEIGHT_MEASURE              1731
#define IDC_H1                          1747
#define IDC_H2                          1748
#define IDC_H3                          1749
#define IDC_H4                          1750
#define IDC_X1                          1751
#define IDC_X2                          1752
#define IDC_W                           1753
#define IDC_X6                          1754
#define IDC_PIER_LAYOUT                 1811
#define IDC_H1_UNIT                     1812
#define IDC_H1_LABEL                    1813
#define IDC_H2_LABEL                    1814
#define IDC_H2_UNIT                     1815
#define IDC_H3_LABEL                    1816
#define IDC_H3_UNIT                     1817
#define IDC_H4_LABEL                    1818
#define IDC_H4_UNIT                     1819
#define IDC_X1_LABEL                    1820
#define IDC_X1_UNIT                     1821
#define IDC_X2_LABEL                    1822
#define IDC_X2_UNIT                     1823
#define IDC_W_UNIT                      1824
#define IDC_X5_UNIT                     1828
#define IDC_W_LABEL                     1829
#define IDC_X3                          1830
#define IDC_X3_UNIT                     1831
#define IDC_X4                          1832
#define IDC_X4_UNIT                     1833
#define IDC_H                           1836
#define IDC_H_UNIT                      1837
#define IDC_X5_LABEL                    1847
#define IDC_X6_UNIT                     1848
#define IDC_X6_LABEL                    1849

#define IDC_BRIDGE                     1850
#define IDC_BRIDGEID                   1851
#define IDC_JOBNUMBER                  1852
#define IDC_ENGINEER                   1853
#define IDC_COMPANY                    1854
#define IDC_COMMENTS                   1855
#define IDC_SHOW_DIALOG                1856

#define ID_EDIT_PROJECT_NAME            50000
#define ID_EDIT_PIER                    50001
#define ID_EDIT_OPTIONS                 50002
#define ID_PROPERTIES                   50006
#define ID_FILE_PROJECT_PROPERTIES      50007
#define ID_EDIT_PROPERTIES              50008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         50009
#define _APS_NEXT_CONTROL_VALUE         326
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
