//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProjectAgent.rc
//
#define EAFID_INDICATOR_MODIFIED        1
#define EAFID_INDICATOR_STATUS          2
#define EAF_TOOLBAR_MENU_COUNT          40
#define EAF_REPORT_MENU_COUNT           50
#define EAF_GRAPH_MENU_COUNT            50
#define IDS_PROJNAME                    100
#define IDR_PROJECTAGENT                101
#define IDS_NWC_MESSAGE                 101
#define IDR_PROJECTAGENTMODULE          102
#define IDS_LWC_MESSAGE                 102
#define IDD_PIER_LAYOUT_PAGE            106
#define IDR_EDIT_MENU                   201
#define IDD_BEARINGS_PAGE               202
#define IDD_SUPERSTRUCTURE_LAYOUT_PAGE  204
#define IDC_COLUMN_COUNT                205
#define IDD_LIVE_LOAD_REACTIONS         205
#define IDC_LF_PERMIT_ROUTINE           208
#define IDC_DECK_ELEVATION              211
#define IDC_DECK_ELEVATION_UNIT         212
#define IDC_CPO                         213
#define IDC_CPO_UNIT                    214
#define IDC_BLO                         215
#define IDC_BLO_UNIT                    216
#define IDC_SKEW                        217
#define IDC_BEARING_LINE_COUNT          218
#define IDC_BACK_REF_BEARING_LIST       219
#define IDC_AHEAD_REF_BEARING_LIST      220
#define IDC_BACK_REF_BEARING_LOCATION   221
#define IDC_AHEAD_REF_BEARING_LOCATION  222
#define IDC_BACK_REF_BEARING_LOCATION_UNIT 223
#define IDC_AHEAD_REF_BEARING_LOCATION_UNIT 224
#define IDC_BACK_REF_BEARING_DATUM      225
#define IDC_AHEAD_REF_BEARING_DATUM     226
#define IDC_ADD_BACK                    227
#define IDC_ADD_AHEAD                   228
#define IDC_REMOVE_BACK                 229
#define IDC_REMOVE_AHEAD                230
#define IDC_BACK_LABEL                  231
#define IDC_AHEAD_LABEL                 232
#define IDC_COPY_AHEAD                  233
#define IDC_COPY_BACK                   234
#define IDC_PIER_TYPE                   234
#define IDC_AHEAD_BEARING_LABEL         235
#define IDC_AHEAD_BEARING_LABEL1        236
#define IDC_AHEAD_BEARING_LABEL2        237
#define IDC_AHEAD_BEARING_LABEL3        238
#define IDC_DIMENSIONS                  239
#define IDC_CURB_LINE_MEASUREMENT       240
#define IDC_LCO                         241
#define IDC_LCO_UNIT                    242
#define IDC_RCO                         243
#define IDC_RCO_UNIT                    244
#define IDC_SL                          245
#define IDC_SL_UNIT                     246
#define IDC_SR                          247
#define IDC_LF_LEGAL_SPECIAL            247
#define IDC_SR_UNIT                     248
#define IDC_DW                          250
#define IDC_LF_OPERATING                250
#define IDC_DESIGN_GRID                 251
#define IDC_LEGAL_ROUTINE_GRID          252
#define IDC_LEGAL_SPECIAL_GRID          253
#define IDC_PERMIT_ROUTINE_GRID         254
#define IDC_PERMIT_SPECIAL_GRID         255
#define IDC_DESIGN_ADD                  256
#define IDC_DESIGN_REMOVE               257
#define IDC_REBAR_GRID                  258
#define IDC_ADD_REBAR                   259
#define IDC_LEGAL_ROUTINE_ADD           260
#define IDC_REMOVE_REBAR                260
#define IDC_LEGAL_ROUTINE_REMOVE        261
#define IDC_DC                          261
#define IDC_LOWER_XBEAM_STIRRUP_GRID    261
#define IDC_LEGAL_SPECIAL_ADD           262
#define IDC_FULL_DEPTH_STIRRUP_GRID     262
#define IDC_LEGAL_SPECIAL_REMOVE        263
#define IDC_ADD_LOWER_XBEAM             263
#define IDC_PERMIT_ROUTINE_ADD          264
#define IDC_REMOVE_LOWER_XBEAM          264
#define IDC_PERMIT_ROUTINE_REMOVE       265
#define IDC_ADD_FULL_DEPTH              265
#define IDC_PERMIT_SPECIAL_ADD          266
#define IDC_REMOVE_FULL_DEPTH           266
#define IDC_PERMIT_SPECIAL_REMOVE       267
#define IDC_LF_INVENTORY                268
#define IDC_LF_LEGAL_ROUTINE            269
#define IDC_LF_PERMIT_SPECIAL           270
#define IDC_REBAR_MATERIAL              271
#define IDC_MORE_PROPERTIES             272
#define IDC_CONCRETE_TYPE_LABEL         275
#define IDC_LOWER_XBEAM_LABEL           276
#define IDC_FULL_DEPTH_LABEL            277
#define IDC_LOWER_XBEAM_SYMMETRY        278
#define IDC_LOWER_XBEAM_SYMMETRY2       279
#define IDC_FULL_DEPTH_SYMMETRY         279
#define IDD_CONCRETE_DETAILS            280
#define IDC_CONCRETE_TYPE               281
#define IDC_FC_LABEL                    282
#define IDC_FC                          283
#define IDC_FC_UNIT                     284
#define IDC_DS_TITLE                    285
#define IDC_DS                          286
#define IDC_DS_UNIT                     287
#define IDC_DW_UNIT                     289
#define IDC_MOD_E                       290
#define IDC_EC                          291
#define IDC_EC_UNIT                     292
#define IDC_AGG_SIZE                    293
#define IDC_AGG_SIZE_UNIT               294
#define IDD_AASHTO_CONCRETE             500
#define IDC_EC_K1_LABEL                 501
#define IDC_EC_K1                       502
#define IDC_EC_K2_LABEL                 503
#define IDC_EC_K2                       504
#define IDC_CREEP_K1_LABEL              505
#define IDC_CREEP_K1                    506
#define IDC_CREEP_K2_LABEL              507
#define IDC_CREEP_K2                    508
#define IDC_SHRINKAGE_K1_LABEL          509
#define IDC_SHRINKAGE_K1                510
#define IDC_SHRINKAGE_K2_LABEL          511
#define IDC_SHRINKAGE_K2                512
#define IDC_HAS_AGG_STRENGTH            513
#define IDC_AGG_STRENGTH                514
#define IDC_AGG_STRENGTH_T              515
#define IDC_CONDITION_FACTOR            1260
#define IDC_CONDITION_FACTOR_TYPE       1407
#define IDC_X5_MEASUREMENT              1423
#define IDC_BACK_BEARING_GRID           1475
#define IDC_AHEAD_BEARING_GRID          1476
#define IDC_REFCOLUMN                   1546
#define IDC_S                           1594
#define IDC_S_LABEL                     1595
#define IDC_X5                          1617
#define IDC_HEIGHT_MEASURE              1731
#define IDC_H1                          1747
#define IDC_H2                          1748
#define IDC_H3                          1749
#define IDC_H4                          1750
#define IDC_X1                          1751
#define IDC_X2                          1752
#define IDC_W                           1753
#define IDC_COLUMN_COUNT_SPINNER        1810
#define IDC_PIER_LAYOUT                 1811
#define IDC_H1_UNIT                     1812
#define IDC_H1_LABEL                    1813
#define IDC_H2_LABEL                    1814
#define IDC_H2_UNIT                     1815
#define IDC_H3_LABEL                    1816
#define IDC_H3_UNIT                     1817
#define IDC_H4_LABEL                    1818
#define IDC_H4_UNIT                     1819
#define IDC_X1_LABEL                    1820
#define IDC_X1_UNIT                     1821
#define IDC_X2_LABEL                    1822
#define IDC_X2_UNIT                     1823
#define IDC_W_UNIT                      1824
#define IDC_X5_UNIT                     1828
#define IDC_W_LABEL                     1829
#define IDC_X3                          1830
#define IDC_X3_UNIT                     1831
#define IDC_X4                          1832
#define IDC_X4_UNIT                     1833
#define IDC_S_UNIT                      1835
#define IDC_H                           1836
#define IDC_H_UNIT                      1837
#define IDC_COLUMN_SHAPE                1838
#define IDC_B_LABEL                     1839
#define IDC_B                           1840
#define IDC_B_UNIT                      1841
#define IDC_D_LABEL                     1842
#define IDC_D                           1843
#define IDC_D_UNIT                      1844
#define IDC_EC_LABEL                    1846
#define EAF_RESERVED_COMMAND_BASE       0x8000
#define EAFID_EDIT_UNITS                32774
#define ID_EDIT_PROJECT_NAME            50000
#define ID_EDIT_PIER                    50002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         50003
#define _APS_NEXT_CONTROL_VALUE         279
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
